    - name: create/copy home page
      #ignore_errors: false
      copy:
        #src: homepage.html #create hp in master node
        content: "This web page created using ansible PB task"
        dest: /var/www/html/index.html
    - name: generta
      shell: uptime > /tmp/uptime.txt